# Generated by Django 2.2.4 on 2019-08-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Game ID')),
                ('name', models.CharField(max_length=80, verbose_name='The name of the game')),
                ('description', models.TextField(max_length=500, verbose_name='Description of the game')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price of the game')),
                ('available', models.BooleanField(default=False, verbose_name='Whether the game is available for purchase or not')),
                ('hidden', models.BooleanField(default=False, verbose_name='Whether the game is listed in the store of not')),
                ('image_cover', models.CharField(blank=True, max_length=300, verbose_name='URI to the game cover image')),
                ('image_banner', models.CharField(blank=True, max_length=300, verbose_name='URI to the game banner image')),
            ],
        ),
    ]
