# Generated by Django 2.2.4 on 2019-08-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_streaming', '0002_auto_20190815_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Whether the game is hidden in the store of not'),
        ),
    ]
