# Generated by Django 2.2.4 on 2019-08-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_streaming', '0003_auto_20190815_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='editor',
            field=models.CharField(default='a', max_length=40, verbose_name='The editor of the game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.CharField(default='b', max_length=40, verbose_name='The publisher of the game'),
            preserve_default=False,
        ),
    ]
