# Generated by Django 2.2.4 on 2019-08-15 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_streaming', '0004_auto_20190815_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='price',
        ),
    ]
