# Generated by Django 2.2.4 on 2019-08-15 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_streaming', '0006_auto_20190815_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLibraryGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateField(auto_now=True, verbose_name='The date the user added the game to its library')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_streaming.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
