# Generated by Django 2.2.4 on 2019-08-15 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_streaming', '0007_userlibrarygame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('\\w+', "The only available chars are: a-z, A-Z, 0-9 and '_'.")], verbose_name='Game ID'),
        ),
    ]
