# Generated by Django 2.2.4 on 2019-08-17 15:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_streaming', '0008_auto_20190816_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('\\w+', "The only available chars are: a-z, A-Z, 0-9 and '_'")], verbose_name='Game ID'),
        ),
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the image')),
                ('version', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('\\d+([\\.\\-_]\\d+)*', "Version number is made using digits possibly separated by '.', '-' or '_'")], verbose_name='Version of the image')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='game_streaming.Game')),
            ],
        ),
        migrations.CreateModel(
            name='GameContainer',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Container ID')),
                ('is_in_use', models.BooleanField(verbose_name='Whether the container is used at this time')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='game_streaming.GameImage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
