# Generated by Django 2.2.4 on 2019-08-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_streaming', '0009_auto_20190817_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='editor',
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.CharField(default='Mojang AB', max_length=40, verbose_name='The developer of the game'),
            preserve_default=False,
        ),
    ]
