# Generated by Django 2.2.4 on 2019-08-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_streaming', '0011_gamecontainer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecontainer',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Container name'),
        ),
    ]
